;;;; Emacs Bookmark Format Version 1;;;; -*- coding: utf-8-emacs; mode: lisp-data -*-
;;; This format is meant to be slightly human-readable;
;;; nevertheless, you probably don't want to edit it.
;;; -*- End Of Bookmark File Format Version Stamp -*-
(("org-refile-last-stored"
  (filename . "~/org/agenda/tasks.org")
  (front-context-string . "* TODO test     ")
  (rear-context-string . "2026-10-05 Mon>\n")
  (position . 1282)
  (last-modified 27323 56771 477533 931000))
("org-capture-last-stored"
 (filename . "~/org/agenda/inbox.org")
 (front-context-string . "** TODO test    ")
 (rear-context-string)
 (position . 10)
 (last-modified 27323 56631 683115 825000))
)
