#!/bin/sh

case "$(file -b --mime-type "$1")" in
    image/*)
        imv "$1" >/dev/null 2>&1 &
        ;;
    application/pdf)
        zathura "$1" >/dev/null 2>&1 &
        ;;
    text/*|application/json|application/x-empty)
        nvim "$1"
        ;;
    *)
        xdg-open "$1" >/dev/null 2>&1 &
        ;;
esac
