[icon]
globs = []
dirs = []
files = []
exts = []
conds = []

[mgr]
border_symbol = " "
border_style.hidden = true

[mode]
normal_main = { fg = "black", bg = "cyan", bold = true }
normal_alt  = { fg = "white", bg = "black" }

select_main = { fg = "black", bg = "cyan", bold = true }
select_alt  = { fg = "white", bg = "black" }

unset_main  = { fg = "black", bg = "cyan", bold = true }
unset_alt   = { fg = "white", bg = "black" }

[tabs]
active   = { fg = "black", bg = "cyan", bold = true }
inactive = { fg = "white", bg = "black" }
