# General
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix
set -g mouse on
set -g history-limit 50000
set -sg escape-time 0
set -g base-index 1
setw -g pane-base-index 1

# Panes
bind c new-window -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# Copy mode
setw -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# Status bar
set -g status-position top
set -g status-justify centre
set -g status-left "#[fg=#646477] #S "
set -g status-right ""
set -g status-style "bg=default,fg=#50505e"
set -g window-status-style "bg=default,fg=#50505e,italics"
set -g window-status-current-style "bg=default,fg=#dedee6,bold,italics"
set -g window-status-format " #I:#W "
set -g window-status-current-format " #I:#W "

# Borders
set -g pane-border-style "fg=#282830"
set -g pane-active-border-style "fg=#545464"
set -g message-style "bg=default,fg=#dedee6,italics"
