# General
unbind C-b
set-option -g prefix C-g
bind-key C-g send-prefix
set -g mouse on
set -g history-limit 50000
set -sg escape-time 0
set -g base-index 1
setw -g pane-base-index 1
set -gq allow-passthrough on
set -g focus-events on
set -g set-clipboard on
set -g renumber-windows on

# Terminal & True Color
set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-ghostty:RGB"
set -ag terminal-overrides ",xterm-ghostty:Tc"

# Panes
bind c new-window -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# Copy mode
setw -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "wl-copy"
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi V send-keys -X select-line

# Status bar configuration
set -g status-position top
set -g status-justify centre
set -g status-style bg=default,fg=default

# Left side: Session number only, no background
set -g status-left-length 10
set -g status-left " #S "

# Right side: Disabled
set -g status-right ""

# Window status format (Plain text, bold current window)
set-window-option -g window-status-format " #I:#W "
set-window-option -g window-status-current-format "#[bold] #I:#W #[default]"
