# General
unbind C-b
set-option -g prefix C-f
bind-key C-f send-prefix
set -g mouse on
set -g history-limit 50000
set -sg escape-time 0
set -g base-index 1
setw -g pane-base-index 1

# Panes
bind c new-window -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# Copy mode
setw -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# Status bar
set -g status-position top
set -g status-justify centre

set -g status-left "#[fg=#E0E2EA] #S "
set -g status-right ""

set -g status-style "bg=#14161B,fg=#E0E2EA"

set -g window-status-style "bg=#14161B,fg=#9B9EA4"
set -g window-status-current-style "bg=#14161B,fg=#EEF1F8"

set -g window-status-format "#[bold,italics] #I:#W "
set -g window-status-current-format "#[bold,italics] #I:#W "

# Borders
set -g pane-border-style "fg=#2C2E33"
set -g pane-active-border-style "fg=#8CF8F7"

# Messages
set -g message-style \
    "bg=#2C2E33,fg=#E0E2EA"
